version: 2

models:
    - name: data2
      description: "Data model"
      columns:
          - name: date
            description: "The primary key for this table"
            tests:
                - not_null
          - name: user_id
            description: "The primary key for this table"
            tests:
                - not_null
          - name: user_uid
            description: "The primary key for this table"
            tests:
                - not_null
          - name: leads
            description: "leads"
          - name: lead_stage2
            description: "lead stage 2"
          - name: lead_stage3
            description: "lead stage 3"
          - name: sql
            description: "sql"
          - name: new_customers
            description: "new customers"
          - name: lost_customers
            description: "lost customers"
          
